"""empty message

Revision ID: ae1fb18a7629
Revises: 
Create Date: 2023-09-15 13:27:54.889776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1fb18a7629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.String(length=64), nullable=True),
    sa.Column('owner_phone', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('vet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vet_id'], ['vets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    op.drop_table('vets')
    # ### end Alembic commands ###
